---
- name: Install packages
  apt:
    name:
      - emacs
      - shellcheck
      - tmux
      - zsh
      - mc
      - git

- name: Install potential packages
  apt:
    name:
      - meld
      - gitk
      - gitg
      - git-cola
    
- name: Install Python-based packages
  pip:
    name:
      - awscli
      - cfn-lint
    executable: pip3
