---
- name: Install packages
  apt:
    name:
      - emacs
      - shellcheck
      - tmux
      - zsh

- name: Install Python-based packages
  pip:
    name:
      - awscli
      - cfn-lint
    executable: pip3
