#!/bin/bash
#############################################################
# This script installs Ansible to the current host.
#############################################################

sudo apt-get -y install python3 python3-pip
sudo -H pip3 install ansible
